# 베이스 이미지 선택
FROM python:3.11-slim

# 작업 디렉터리 설정
WORKDIR /app

# 프로젝트 파일 복사
COPY . .

# 필요 라이브러리 설치
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# 서버 실행 명령어
CMD ["python", "poo.py"]
