name: Deploy Discord Bot to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup SSH and Deploy to EC2
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd ~/discord-bot
          git pull origin main
          docker stop discord-bot-container || true
          docker rm discord-bot-container || true
          docker build -t my-discord-bot .
          docker run -d --restart always --name discord-bot-container \
            -e DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }} \
            -e RIOT_API_KEY=${{ secrets.RIOT_API_KEY }} \
            my-discord-bot